

SCREEN_W, SCREEN_H = 800, 600
SCREEN_SIZE = (SCREEN_W, SCREEN_H)
GROUND_HEIGHT = SCREEN_H - 62

BG_MULTI = 2.68
PLAYER_MULTI = 3.0
BRICK_MULTI = 2.69
ENEMY_MULTI = 2.5
ENEMY_SPEED = 1

GRAVITY = 0.8
ANTI_GRAVITY = 0.8

FONT = 'LithosPro-Black.otf'